[package]
name = "fold_files"
version = "0.1.1"
authors = ["Stephan Creutz <stephan.cr@gmx.de>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["cargo", "deprecated"] }

[profile.release]
lto = true
panic = 'abort'
